### ISSUE TITLE
unit tests fail

### ISSUE THREAD

**Issue by magwas** [oliverbarnes/old-participate-client#80]
Looking at .tavis.yml, after installing everything which seems to be needed I got the error below.
I see travis is also failing for a long time.
$ npm test

> participate-frontend@0.0.0 test /home/mag/project/Alkotmany/participate-frontend
> ember test

version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
Building...
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mag/project/Alkotmany/participate-frontend/Brocfile.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.loadBrocfile (/usr/lib/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:147:14)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

**Comment by oliverbarnes** [comment]
Hi @magwas, yeah the build has been failing ever since updating ember-cli. I've been working on the test suite on a separate branch, migrating to ember-cli-mocha, and I hope to have the build working again in a few days.

I never got your error, though... Googling it I found [this thread on the ember forum](http://discuss.emberjs.com/t/could-not-find-watchman-falling-back-to-nodewatcher-for-file-system-events/6873/5), see if it helps at all?

**Comment by oliverbarnes** [comment]
@magwas I've just merged my changes to the test suite, and travis is passing now. Closing this, Let me know if it doesn't work for you
